# Generated by Django 3.1.1 on 2020-09-18 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fiat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_price', models.FloatField(null=True)),
                ('perc_change', models.FloatField(null=True)),
                ('is_above', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('crypto_curr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.crypto')),
                ('fiat_curr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.fiat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
