# Generated by Django 3.1.1 on 2020-09-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_auto_20200921_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='crypto_curr',
            new_name='crypto_id',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='fiat_curr',
            new_name='fiat_id',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='user',
            new_name='user_id',
        ),
    ]
