# Generated by Django 3.1.1 on 2020-09-23 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_auto_20200923_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alert.alerttype'),
        ),
    ]
