# Generated by Django 3.1.1 on 2020-09-23 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_auto_20200923_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_type',
        ),
        migrations.AddField(
            model_name='alert',
            name='alerttype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alert.alerttype'),
            preserve_default=False,
        ),
    ]
