# Generated by Django 3.1.1 on 2020-09-23 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_auto_20200923_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alerttype',
        ),
    ]
