# Generated by Django 3.1.1 on 2020-09-23 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_remove_alert_alerttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alert.alerttype'),
            preserve_default=False,
        ),
    ]
