# Generated by Django 3.1.1 on 2020-09-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0008_alert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='desired_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
