# Generated by Django 3.1.1 on 2020-09-21 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fiat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('rate', models.FloatField()),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('crypto_curr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.crypto')),
                ('fiat_curr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.fiat')),
            ],
        ),
    ]
