# Generated by Django 3.1.1 on 2020-09-23 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20200921_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('crypto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.crypto')),
                ('fiat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.fiat')),
            ],
        ),
    ]
