# Generated by Django 3.1.1 on 2020-09-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_auto_20200924_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fiat',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
