# Generated by Django 3.1.1 on 2020-09-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_auto_20200924_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinhistory',
            old_name='value',
            new_name='rate',
        ),
    ]
